// src/core/parser/profile-fingerprint.test.ts
import { describe, expect, it } from 'bun:test';
import { computeFingerprint, matchProfile, matchProfileFromRows } from './profile-fingerprint';
import type { ImportProfile } from '../../shared/types';

// ── computeFingerprint ───────────────────────────────────────────────────────

describe('computeFingerprint', () => {
  it('5.1 — determinism: same columns in different order produce the same fingerprint', () => {
    const a = computeFingerprint(['Date', 'Amount', 'Description']);
    const b = computeFingerprint(['Description', 'Amount', 'Date']);
    expect(a).toBe(b);
  });

  it('5.2 — whitespace stripping: leading/trailing spaces are ignored', () => {
    const a = computeFingerprint(['  Date  ', 'Amount']);
    const b = computeFingerprint(['Date', 'Amount']);
    expect(a).toBe(b);
  });

  it('5.3 — case normalization: uppercase and lowercase produce the same fingerprint', () => {
    const a = computeFingerprint(['DATE', 'AMOUNT']);
    const b = computeFingerprint(['date', 'amount']);
    expect(a).toBe(b);
  });

  it('5.4 — different columns produce different fingerprints', () => {
    const a = computeFingerprint(['Date', 'Amount']);
    const b = computeFingerprint(['Date', 'Description']);
    expect(a).not.toBe(b);
  });

  it('5.5 — empty header row: returns a string, does not throw', () => {
    const result = computeFingerprint([]);
    expect(typeof result).toBe('string');
    expect(result.length).toBe(64); // SHA-256 hex is always 64 chars
  });
});

// ── matchProfile ─────────────────────────────────────────────────────────────

function makeProfile(overrides: Partial<ImportProfile> & { id: string }): ImportProfile {
  return {
    name: 'Test Bank',
    bankName: 'Test Bank',
    csvDelimiter: ',',
    columnMap: { date: 'date', amount: 'amount', description: 'description' },
    dateFormat: 'dd/mm/yyyy',
    amountMultiplier: 1,
    headerRowOffset: 0,
    fingerprint: computeFingerprint(['date', 'amount', 'description']),
    ...overrides,
  };
}

describe('matchProfile', () => {
  it('5.6 — exact match: returns the matching profile with match=exact', () => {
    const headerRow = ['Date', 'Amount', 'Description'];
    const profile = makeProfile({
      id: 'p1',
      fingerprint: computeFingerprint(headerRow),
    });
    const result = matchProfile(headerRow, [profile]);
    expect(result).toEqual({ match: 'exact', profile });
  });

  it('5.7 — partial match: same column count but different fingerprint', () => {
    // Profile has 3 columns mapped; incoming header also has 3 non-empty columns but different names
    const headerRow = ['Date', 'Amount', 'Reference'];
    const profile = makeProfile({
      id: 'p2',
      columnMap: { date: 'date', amount: 'amount', description: 'description' }, // 3 keys
      fingerprint: computeFingerprint(['__non_matching_placeholder__']), // valid 64-char SHA-256, won't match headerRow
    });
    // Fingerprint doesn't match exact but column count (3) matches
    const result = matchProfile(headerRow, [profile]);
    expect(result).toEqual({ match: 'partial', profile });
  });

  it('5.8 — no match: empty profiles array returns { match: none }', () => {
    const result = matchProfile(['Date', 'Amount'], []);
    expect(result).toEqual({ match: 'none' });
  });

  it('5.9 — exact wins over partial: exact match is returned even when a partial match also exists', () => {
    const headerRow = ['Date', 'Amount', 'Description'];
    const exactFingerprint = computeFingerprint(headerRow);

    const exactProfile = makeProfile({
      id: 'exact',
      fingerprint: exactFingerprint,
      columnMap: { date: 'date', amount: 'amount', description: 'description' },
    });
    const partialProfile = makeProfile({
      id: 'partial',
      fingerprint: computeFingerprint(['__non_matching_placeholder__']), // valid 64-char SHA-256, won't match headerRow
      columnMap: { date: 'date', amount: 'amount', description: 'description' },
    });

    const result = matchProfile(headerRow, [partialProfile, exactProfile]);
    expect(result).toEqual({ match: 'exact', profile: exactProfile });
  });

  it('5.10 — empty profiles array: returns { match: none }, does not throw', () => {
    expect(() => matchProfile([], [])).not.toThrow();
    const result = matchProfile([], []);
    expect(result).toEqual({ match: 'none' });
  });

  it('5.11 — saved headerRowOffset is applied before fingerprinting when scanned rows include frontmatter', () => {
    const profile = makeProfile({
      id: 'offset-profile',
      headerRowOffset: 2,
      fingerprint: computeFingerprint(['Date', 'Amount', 'Description']),
    });

    const result = matchProfileFromRows(
      ['Generated by bank'],
      [profile],
      [
        ['Bank export'],
        ['Generated by bank'],
        ['Date', 'Amount', 'Description'],
        ['2026-01-01', '-2.80', 'Coffee'],
      ],
    );

    expect(result).toEqual({ match: 'exact', profile });
  });
});
